baseURL = "https://augustebaum.github.io/website"
languageCode = "en-us"
title = "Auguste's website"
theme = "cactus"
copyright = "Auguste Baum" # cactus will use title if copyright is not set

# disqusShortname = "example" # Used when comments is enabled. Cactus will use site title if not set
# googleAnalytics = "UA-1234-5"
# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4
  [markup.goldmark.renderer]
    unsafe = true


[params]
  colortheme = "white" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default
  showAllPostsArchive = false # default

  # Home page settings
  # Multi-line strings are interpreted as code, unfortunately
  # description = """
  #   My name is Auguste Baum.
  #   In case you were wondering, my first name is pronounced like the eighth month of the year.
  #   I am currently a Master's student in Data Science at EPFL, in Switzerland.
    
  #   I have also been involved with [Resilio](hh.com), a start-up aiming to help companies reduce their environmental impact.
  # """
  description = "My name is Auguste Baum. In case you were wondering, my first name is pronounced like the eighth month of the year. I have just graduated with a Master's degree in Data Science at EPFL, in Switzerland. I have also been involved with [Resilio](https://www.resilio.tech), a start-up aiming to help companies reduce their environmental impact."
  mainSection = "posts"
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = false
  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "https://codeberg.org/augustebaum" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = true
  showReadTime = true

  [params.comments]
    enabled = false # disabled for now
    engine = "cactus_comments" # only disqus, utterances, and cactus_comments is supported
    [params.comments.utterances]
      repo = "<github_username>/<github_reponame>"
      label = "hugo-site-name" # you can use however you want to label your name in your repo's issues
      theme = "github-light"
    [params.comments.cactuscomments]
      siteName = "your_cactus_comments_sitename" # see https://cactus.chat/ on how to register your site name
      #serverUrl = "" # Defaults to https://matrix.cactus.chat:8448 (Cactus Chat public server)
      #serverName = "" # Defaults to cactus.chat

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/augustebaum"
  # [[params.social]]
  #   name = "gitlab"
  #   link = "https://gitlab.com/augustebaum"
  [[params.social]]
    name = "email"
    link = "auguste.baum@pm.me" # no need for "mailto:" at the start
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/auguste-baum/"
