baseURL = "https://augustebaum.github.io"
languageCode = "en-us"
title = "Auguste Baum's website"
theme = "etch"

[params]
  description = "Auguste Baum's website"
  copyright = "Copyright © 2024 Auguste Baum"
  dark = "auto"
  highlight = true

# Main menu which appears below site header.
[menu]
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "RSS"
  url = "/index.xml"
  weight = 5

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = true
    startLevel = 2

  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4

  [markup.goldmark.renderer]
    unsafe = true
